// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYbvDT-NOqhNu9TgIDvJdoVswfdw-JSg',
    appId: '1:101643469100:web:da9e49be928d7f8d61ec89',
    messagingSenderId: '101643469100',
    projectId: 'anime-verse-project',
    authDomain: 'anime-verse-project.firebaseapp.com',
    storageBucket: 'anime-verse-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAD0YdXgclZjT9LqG0KNxTgZ2vKlxVLhU',
    appId: '1:101643469100:android:7ce34de6eca0ec1a61ec89',
    messagingSenderId: '101643469100',
    projectId: 'anime-verse-project',
    storageBucket: 'anime-verse-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXaNSzSxQdx1ffJG2mz5DmzDarHM-tl8',
    appId: '1:101643469100:ios:3c2fcc2a11f2effe61ec89',
    messagingSenderId: '101643469100',
    projectId: 'anime-verse-project',
    storageBucket: 'anime-verse-project.firebasestorage.app',
    iosBundleId: 'com.example.animeVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzXaNSzSxQdx1ffJG2mz5DmzDarHM-tl8',
    appId: '1:101643469100:ios:3c2fcc2a11f2effe61ec89',
    messagingSenderId: '101643469100',
    projectId: 'anime-verse-project',
    storageBucket: 'anime-verse-project.firebasestorage.app',
    iosBundleId: 'com.example.animeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqYbvDT-NOqhNu9TgIDvJdoVswfdw-JSg',
    appId: '1:101643469100:web:6dc90574f14148d761ec89',
    messagingSenderId: '101643469100',
    projectId: 'anime-verse-project',
    authDomain: 'anime-verse-project.firebaseapp.com',
    storageBucket: 'anime-verse-project.firebasestorage.app',
  );
}
